### ISSUE TITLE
Add City, Zip, FIPS, Lat & Lng to Agencies table

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#100]
# Goal
We will have to manually go through and add the relevant information to each [agency](https://www.dolthub.com/repositories/pdap/datasets/data/master/agencies). Once this is all done, it will give front-end devs a way to accurately place a pin for every agency in the US!

This issue can be closed once all agencies have the appropriate data—until then, we will need a lot of contributions.

# Process:
- Reference our [dolt docs](https://docs.pdap.io/components/data-collection/dataset-catalog/submit-or-update-datasets) for information / context
- Fork and clone the [datasets repo](https://www.dolthub.com/repositories/pdap/datasets)
- Navigate into the cloned directory and start a `dolt sql-server` ([docs here](https://docs.dolthub.com/interfaces/cli#dolt-sql-server))
- Use a GUI tool like DBeaver or TablePlus for ease of data entry and connect to your localhost server
- Pick a state, I started with Alaska (AK).
- Copy the name of the agency, google their name to get the address of the main office/district
- Copy the address into Google Maps. Copy the city and 5 digit ZIP code into the table 
- Right click on the map of the agency to display the coordinates. Copy those into lat, lng (google copies both fyi)
- Use the coordinates [here](https://geo.fcc.gov/api/census/#!/area/get_area) to get the right `county_fips`
- Repeat for the rest of the agencies in that state, then commit and create a PR in DoltHub!

# Update 5/22
There is now a tool [here](https://github.com/ncpierson/pdad-agency-locator) (thank you @ncpierson) which scrapes Geonames for this info.

**Comment by ncpierson** [comment]
I've started attempting an automated way to gather this data using [Geonames](http://www.geonames.org/).
You can see my repository here: https://github.com/ncpierson/pdad-agency-locator

I estimate about 30-50% coverage using *exact* name matching, but geonames data only overs fips, lat, and lng but not address or zip.

**Comment by EricTurner3** [comment]
Fantastic work @ncpierson ! I was hoping someone could find a geolocation service, I knew that Google would be expensive. But I'm stoked you already were able to pull a state's worth of data! I merged that PR into our master dolt branch. Good news is, even if there are some discrepancies, someone who is local and actually knows the PD can always make a PR and correct it!

**Comment by josh-chamberlain** [comment]
@ncpierson just FYI that we have a [data bounty going on](https://www.dolthub.com/repositories/pdap/datasets/bounties/3c259649-762e-438b-a538-b14be4d0507a)! Going to close this issue as that's now where people should go to submit data.
