### ISSUE TITLE
Create a Socrata scraper

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#120]
Socrata's a common publisher. A common scraper would take us a long way.

https://data.cityofberkeley.info/Public-Safety/Berkeley-PD-Log-Arrests/xi7q-nji6
https://dev.socrata.com/publishers/https://dev.socrata.com/docs/endpoints.html

**Comment by CaptainStabs** [comment]
[opendata scraper](https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/blob/main/Base_Scripts/Scrapers/opendata/opendata_scraper.py) supports this.
