### ISSUE TITLE
Create the first properly configured scraper

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#121]
# Feature
Configure a scraper to the new paradigm from https://github.com/Police-Data-Accessibility-Project/planning/issues/146.

Doing this with any scraper will close the issue.

# Candidates

## Minneapolis
https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/pull/111
Then, we should run this scraper and add these incident reports, traffic stops, and shots fired to data-intake.

## St. Louis
The Bounty Hunters are working on this right now.

## Pittsburgh
#167

**Comment by CaptainStabs** [comment]
What does it mean by `The Bounty Hunters are working on this right now.` ?
