### ISSUE TITLE
Centralize the fields.txt

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#129]
Let's look at the scrapers we have and the fields they scrape, to see what we can learn from them. 

Each scraper has a fields.txt.

**Comment by CaptainStabs** [comment]
Altering this should accomplish this goal. 
https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/blob/main/common/utils/demo_utils/field_extractor.py
