### ISSUE TITLE
DoltPy and camelot packages have dependency conflict

### ISSUE THREAD

**Issue by RenatoLopes771** [Police-Data-Accessibility-Project/PDAP-Scrapers#150]
Here's an image of the issue:
[
![image](https://user-images.githubusercontent.com/52989307/133093310-11706c7a-621b-454d-8428-d5b7879a7296.png)
](url)

This was acquired when attempting to install requirements.txt on a fresh remote repo

**Comment by boonepeter** [comment]
+1 to this. 

Using `Python 3.10.1 v3.10.1:2cd268a3a9`

```
ERROR: Cannot install -r requirements.txt (line 11) and -r requirements.txt (line 6) because these package versions have conflicting dependencies.

The conflict is caused by:
    camelot 12.6.29 depends on SQLAlchemy<0.8.0 and >=0.7.7
    doltpy 2.0.7 depends on SQLAlchemy==1.3.18
```

**Comment by josh-chamberlain** [comment]
closed as we're no longer using dolthub for primary data storage
