### ISSUE TITLE
Create Archive snapshot of dataset url when Scrapers are run

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#180]
This should ping the internet archive with a request to archive the site at the time the scraper should run.

- https://archive.org/services/docs/api/
- we shouldn't bother creating an archive if the scraper didn't run successfully

> from archive-it:
> 
> While we would love to have y’all as an Archive-It partner, I think this specific request may be better suited for our Wayback Machine’s "Save Page Now" (SPN) functionality. I’ve found a few resources on SPN API integrations that might fit your needs. Here is the standard API info page: https://archive.org/help/wayback_api.php. Here is our developer wiki: https://archive.readme.io/docs/overview. I also found this resource for a python wrapper for SPN: https://github.com/palewire/savepagenow.
> 
> Please let me know if you find something here that works for you so I can share with the team and anyone else who may have a similar request in the future! If not, I can reach out to some of my colleagues in our patron services division to see if they have other suggestions, or simply connect you someone.

**Comment by CaptainStabs** [comment]
The main issue that I can foresee is that the scraper will have to know its ID before it's run in order to pass it to the archival script. The archival script needs to know either the `dataset_id` or `scraper_id` so that it can access the proper dataset within the schema and add the archived URL there.

**Comment by josh-chamberlain** [comment]
If the scraper needs to know its ID before it can be run, it sounds like the process goes something like this:

1. someone writes a scraper.
2. part of the `scraper.py` file includes reference to the scraper's UUID, which is required for submission.
3. part of the scraper process includes a requirement to add a scraper ID to the scrapers table in DoltHub, linking the scraper and dataset by ID in our relational database.
4. scraper submissions can only be accepted to our intake API if the scraper ID exists in the DoltHub database (this would be validated as part of running the scraper).

so a scraper can be run without this UUID, but the results will not be submitted to the API. I could download an run a scraper for personal use in this scenario.

as far as terminology, that's fine—`archives` is sensible. I will need to do some work to change "Extractions" to "Archive" everywhere, which I can take care of in the next couple days.

i think `dataset_snapshot` makes more sense than `website_archive`. we have a particular definition for "dataset" so this terminology is aligned.

**Comment by CaptainStabs** [comment]
Actually, I take back what I said. I should be able to match the scraper based on the url it provides to the archival script in the schema.

**Comment by CaptainStabs** [comment]
> as far as terminology, that's fine—archives is sensible. I will need to do some work to change "Extractions" to "Archive" everywhere, which I can take care of in the next couple days.

Extractions would be the raw data, not the *archive* of the source of the *dataset*

> i think `dataset_snapshot` makes more sense than `website_archive`. we have a particular definition for "dataset" so this terminology is aligned.
👍

**Comment by CaptainStabs** [comment]
latest branch has the code for this

**Comment by josh-chamberlain** [comment]
@CaptainStabs oh, I see. Yes, I agree, `archive` represents what we create with internet archive, and `extractions` are the raw data generated by the scrapers.

**Comment by josh-chamberlain** [comment]
@CaptainStabs Now that I have seen the branch, I think `dataset_archive` makes the most contextual sense.
