### ISSUE TITLE
highlight examples of things in the repo that work

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#212]
- [x] We tell people how to test in general in the readme, but let's give them a working example or two. This helps people who are new to scraping understand the point.
   - describe the strategy of the scraper ("This collects `type of record` from `department` by `how it works`.") 
   - make sure its readme works
- [x] readme: what are utilities, and why might you use them?
- [x] readme: what are data portal scrapers, and why might you use them?

**Comment by josh-chamberlain** [comment]
@EvilDrPurple now that you're our resident scrapers repo expert, do you have thoughts on an example scraper which could work here? Other than this, all the tasks in #197 are mine.

**Comment by EvilDrPurple** [comment]
Well, in my most humble opinion I believe the scraper I worked on 15 months ago for Pittsburgh data is a good example. It utilized both a data portal scraper and a file downloader util in one file. It appears to still work [Link](https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/blob/main/scrapers/PA/allegheny_county/municipal/pittsburgh/scraper.py)
Other than that, just taking a quick look the Chico, CA college scraper looks like a good example of using the crimegraphics data portal, though the README could use some work as it is just the default template README [Link](https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/tree/main/scrapers/CA/butte_county/college/chico)
The Atlanta, GA scrapers seem to be a decent example of using the list_pdf utils [Link](https://github.com/Police-Data-Accessibility-Project/PDAP-Scrapers/tree/main/scrapers/GA/fulton_county/municipal/atlanta)

Let me know what you think!

**Comment by josh-chamberlain** [comment]
@EvilDrPurple perfect! Thank you for helping us welcome people to the project
