### ISSUE TITLE
Bay County Docker container is broken after changes to folder structure

### ISSUE THREAD

**Issue by OscarVanL** [Police-Data-Accessibility-Project/PDAP-Scrapers#27]
After the changes in https://github.com/Police-Data-Accessibility-Project/Scrapers/pull/24 which created a standardised captcha solver interface and moved the existing captcha solver into a 'common' directory at the project root, this has broken the Bay County Docker container.

Upon starting the container it says:
```
root@81778276cb3c:/scraper# python3 Scraper.py
Traceback (most recent call last):
  File "Scraper.py", line 14, in <module>
    from common.captcha.benchmark.BenchmarkAdditionSolver import CaptchaSolver
ModuleNotFoundError: No module named 'common'
```

I think this is because the container has the app root set in the Bay County/Scraper folder, because the error occurs at the import.

The container needs to be updated to work with the current project structure.

**Comment by mcsaucy** [comment]
So I started poking at this a bit and it's proving to be a little trickier than expected to get it right. Before I continue, let me establish that I have zero prior experience in this, so I could be *completely* wrong.

In a perfect world, we'd have a single container for each of our scrapers/fetchers/binaries/whatever. Those containers would have only what is required (not the entire repo) to keep things lean and easy to reason about. So the `USA/FL/Bay/Court/scraper` container would just have itself and `common`, ideally.

I started playing around with an approach where we'd have a dedicated dockerfile and such for common to handle its dependencies, and then each scraper/fetcher/whatever would be its own service in a top level `docker-compose.yml`, referencing their own docker files (thus managing their own dependencies). They'd also be tied to common (I've been referencing [this](https://cjolowicz.github.io/posts/incremental-docker-builds-for-monolithic-codebases/)). The problem with this approach is it results in us having N entries in this top-level `docker-compose.yml` and that's gonna suck to manage.

It seems like docker-compose doesn't really like looking at parent directories (I can do some context finagling, but `context: ../../../../..` is super gross). I'm presently looking into alternative options for packaging our Python scrapers (like using shiv to get us a singlular artifact we can throw in a container) which may simplify this.
