### ISSUE TITLE
Scrape datasets from Police Open Data Census

### ISSUE THREAD

**Issue by josh-chamberlain** [Police-Data-Accessibility-Project/PDAP-Scrapers#95]
There are a few dozen datasets here, we can use them.

Here's how to add new datasets:
https://docs.pdap.io/components/data-collection/dataset-catalog/submit-or-update-datasets

Here they are:
https://codeforamerica.github.io/PoliceOpenDataCensus/

**Comment by CaptainStabs** [comment]
Consider adding `Machine Readable` as a field within our own dataset

**Comment by josh-chamberlain** [comment]
@CaptainStabs this is now done.

https://www.dolthub.com/repositories/pdap/datasets/query/master?q=describe+datasets&active=Tables

![Screen Shot 2021-05-06 at 11 07 36 AM](https://user-images.githubusercontent.com/30379833/117321608-46eb1300-ae5b-11eb-89a0-8c46a57e1191.png)

**Comment by josh-chamberlain** [comment]
I also added it to the dataset submission template thing.
